name: easy_form_kit
description: A set of widgets for processing form field data in one common processor. Convenient for saving data to a database, sending via API, etc.
version: 1.0.0
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
